# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listview.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pb_close = QtWidgets.QPushButton(self.centralwidget)
        self.pb_close.setGeometry(QtCore.QRect(40, 260, 75, 23))
        self.pb_close.setObjectName("pb_close")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 30, 291, 201))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listView = QtWidgets.QListView(self.verticalLayoutWidget)
        self.listView.setObjectName("listView")
        self.verticalLayout.addWidget(self.listView)
        self.pb_savefile = QtWidgets.QPushButton(self.centralwidget)
        self.pb_savefile.setGeometry(QtCore.QRect(40, 150, 75, 23))
        self.pb_savefile.setObjectName("pb_savefile")
        self.pb_writeformat = QtWidgets.QPushButton(self.centralwidget)
        self.pb_writeformat.setGeometry(QtCore.QRect(40, 180, 75, 23))
        self.pb_writeformat.setObjectName("pb_writeformat")
        self.pb_openfile = QtWidgets.QPushButton(self.centralwidget)
        self.pb_openfile.setGeometry(QtCore.QRect(40, 210, 75, 23))
        self.pb_openfile.setObjectName("pb_openfile")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 30, 81, 21))
        self.label.setObjectName("label")
        self.label_select_path = QtWidgets.QLabel(self.centralwidget)
        self.label_select_path.setGeometry(QtCore.QRect(40, 70, 211, 31))
        self.label_select_path.setObjectName("label_select_path")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(290, 240, 341, 80))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox.setObjectName("checkBox")
        self.horizontalLayout.addWidget(self.checkBox)
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalLayoutWidget)
        self.checkBox_2.setObjectName("checkBox_2")
        self.horizontalLayout.addWidget(self.checkBox_2)
        self.bottomText = QtWidgets.QTextBrowser(self.centralwidget)
        self.bottomText.setGeometry(QtCore.QRect(60, 410, 511, 91))
        self.bottomText.setObjectName("bottomText")
        self.dateTimeEdit = QtWidgets.QDateTimeEdit(self.centralwidget)
        self.dateTimeEdit.setGeometry(QtCore.QRect(40, 320, 194, 22))
        self.dateTimeEdit.setObjectName("dateTimeEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionopen = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/open_folder_lock_128px_1112500_easyicon.net.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionopen.setIcon(icon)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actionexit = QtWidgets.QAction(MainWindow)
        self.actionexit.setObjectName("actionexit")
        self.menu.addAction(self.actionopen)
        self.menu.addAction(self.actionsave)
        self.menu.addAction(self.actionexit)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        self.pb_close.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pb_close.setText(_translate("MainWindow", "关闭窗口"))
        self.pb_savefile.setText(_translate("MainWindow", "创建xls文件"))
        self.pb_writeformat.setText(_translate("MainWindow", "写入格式"))
        self.pb_openfile.setText(_translate("MainWindow", "打开文件"))
        self.label.setText(_translate("MainWindow", "当前选择路径："))
        self.label_select_path.setText(_translate("MainWindow", "filepath"))
        self.checkBox.setText(_translate("MainWindow", "hello world"))
        self.checkBox_3.setText(_translate("MainWindow", "another"))
        self.checkBox_2.setText(_translate("MainWindow", "others"))
        self.menu.setTitle(_translate("MainWindow", "菜单(&M)"))
        self.menu_2.setTitle(_translate("MainWindow", "编辑(&E)"))
        self.actionopen.setText(_translate("MainWindow", "打开"))
        self.actionopen.setShortcut(_translate("MainWindow", "Ctrl+O"))
        self.actionsave.setText(_translate("MainWindow", "保存"))
        self.actionsave.setShortcut(_translate("MainWindow", "Ctrl+S"))
        self.actionexit.setText(_translate("MainWindow", "退出"))
        self.actionexit.setShortcut(_translate("MainWindow", "F4"))

